"""
Analytics Schemas.

Pydantic response models for the admin analytics dashboard endpoint.
All data is aggregated in the database via SQL RPC functions
(migration 007) — no Python-side aggregation is performed.

Response structure:
  GET /admin/analytics
  └── AnalyticsDashboard
      ├── orders: OrderAnalytics   — order counts + revenue totals
      └── top_products: list[TopProduct] — best sellers by units sold
"""
from decimal import Decimal
from uuid import UUID

from pydantic import BaseModel, Field


class OrderAnalytics(BaseModel):
    """
    Aggregated order and revenue statistics across the entire platform.

    Revenue figures only count orders with status='paid'.
    Orders in other states (pending, failed, cancelled) are excluded
    from revenue totals but counted in their respective status buckets.
    """
    # Order counts by status
    total_orders: int = Field(description="Total number of orders ever placed")
    pending_orders: int = Field(description="Orders awaiting payment")
    paid_orders: int = Field(description="Successfully paid orders")
    failed_orders: int = Field(description="Orders where payment failed")
    cancelled_orders: int = Field(description="Cancelled orders")

    # Revenue (paid orders only)
    total_revenue: Decimal = Field(
        description="Lifetime revenue from all paid orders"
    )
    revenue_today: Decimal = Field(
        description="Revenue from paid orders since midnight today (UTC)"
    )
    revenue_this_month: Decimal = Field(
        description="Revenue from paid orders since the start of the current calendar month (UTC)"
    )


class TopProduct(BaseModel):
    """
    A single product entry in the top-sellers list.

    Aggregated from order_items joined to orders where status='paid'.
    """
    product_id: UUID = Field(description="Product UUID")
    product_name: str = Field(description="Product name at the time of the query")
    total_sold: int = Field(description="Total units sold across all paid orders")
    total_revenue: Decimal = Field(
        description="Total revenue generated by this product (quantity × price at order time)"
    )


class AnalyticsDashboard(BaseModel):
    """
    Complete admin analytics dashboard response.

    Returned by GET /admin/analytics.
    Composes order-level and product-level analytics into a single response
    so the dashboard frontend can render everything from one API call.
    """
    orders: OrderAnalytics
    top_products: list[TopProduct] = Field(
        description="Best-selling products ranked by units sold, descending"
    )
